# Project information
site_name: Rarible Protocol
site_description: Rarible Protocol documentation

# Repository
repo_url: https://github.com/rarible/protocol
repo_name: rarible/protocol
edit_uri: ""

# Configuration
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
    - search.highlight
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate

# Plugins
plugins:
  - search

# Customization
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zqsZsEWBbN
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/raribledao
    - icon: fontawesome/brands/github
      link: https://github.com/rarible
  analytics:
    provider: google
    property: G-20ZJ98JPQ3
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by using our <a href="https://github.com/rarible/protocol/issues/new/?title=[Feedback]+{title}+-+{url}" target=_blank>feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeat visits and preferences
      and measure the effectiveness of our documentation and whether users
      find what they're searching for. Thank you for helping us improve the documentation.
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - tables
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.snippets
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - 'Home': 'index.md'
  - 'Protocol Overview':
      - 'Overview': 'overview/protocol-overview.md'
      - 'Tokens, Fees and Royalties': 'overview/tokens-fees-royalties.md'
      - 'Architecture': 'overview/architecture.md'
      - 'API References': 'api-reference.md'
      - 'Lazy Minting': 'overview/lazy-minting.md'
      - 'Indexer': 'overview/indexer.md'
      - 'Auctions': 'overview/auctions.md'
      - 'Status': 'overview/protocol-status.md'
      - 'Next Steps': 'overview/next-steps.md'
  - 'Getting Started':
      - 'Quick Start': 'getting-started/quick-start.md'
      - 'Community and resources': 'getting-started/community.md'
      - 'Tutorials':
        - 'Managing SDK ang connecting blockchain wallets': 'getting-started/managing-sdk.md'
        - 'Example of uploading & using Metadata with IPFS': 'getting-started/ipfs-example.md'
#        - 'Create Sell Order and Accept Bid': 'getting-started/sellOrder_acceptBid.md'
#        - 'Transferring NFTs': 'getting-started/unifiedTransfer.md'
        - 'Setting Up Royalties on an External Collection': 'getting-started/royalties-on-a-external-collection.md'
  - 'Reference':
      - 'Overview': 'reference/reference-overview.md'
      - 'Installation': 'reference/install-sdk.md'
      - 'Wallets': 'reference/wallets.md'
      - 'Create collection': 'reference/create-collection.md'
      - 'Mint': 'reference/mint.md'
      - 'Sell Order': 'reference/order.md'
      - 'Mint and Sell': 'reference/mint-and-sell.md'
      - 'Create and Accept Bid': 'reference/bid.md'
      - 'Transfer': 'reference/transfer.md'
      - 'Burn': 'reference/burn.md'
      - 'Get balance': 'reference/get-balance.md'
      - 'Conversion': 'reference/conversion.md'
      - 'Contract Addresses': 'reference/contract-addresses.md'
      - 'Search Capabilities': 'reference/search-capabilities.md'
  - 'Use Cases':
      - 'Overview': 'use-cases/use-cases-overview.md'
      - 'Picnic': 'use-cases/picnic.md'
      - 'cocoNFT': 'use-cases/coconft.md'
      - 'MintGate': 'use-cases/mintgate.md'
      - 'EZCode SDK plugin': 'use-cases/bubblesdk.md'
      - 'Moralis Lazy Mint & Sell plugin': 'use-cases/moralisplugin.md'
  - 'Features': 'features.md'
